# https://developer.redis.com/create/docker/nodejs-nginx-redis/

version: '3.9'
services:
  redis:
    container_name: redis
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis/data:/data
#  web:
#    restart: on-failure
#    build: ./web
#    ports:
#      - '4000:5000'