# https://developer.redis.com/create/docker/nodejs-nginx-redis/

version: '3.9'
services:
  redis:
    network_mode: host
    container_name: redis
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis/data:/data
  web:
    network_mode: host
    container_name: web1
    image: web1
    build: ./web
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - '3000:3000'
    restart: on-failure
  nginx:
    network_mode: host
    image: nginx_server
    container_name: nginx
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web
