# https://developer.redis.com/create/docker/nodejs-nginx-redis/

version: '3.9'
services:
  redis:
    container_name: redis
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis/data:/data
  web:
    container_name: web1
    image: web1
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - '3000:3000'
    restart: on-failure